# Generated by Django 5.1.2 on 2024-10-21 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='drivers',
        ),
        migrations.RemoveField(
            model_name='car',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='car',
            name='model',
        ),
        migrations.AddField(
            model_name='car',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='car',
            name='license_number',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='car',
            name='manufacturer_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
